# Generated by Django 5.1.4 on 2025-02-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(blank=True, default='tasks_asset/default_images.png', null=True, upload_to='tasks_asset'),
        ),
    ]
